version: '3'
services:
  yaeger:
    image: "jaegertracing/all-in-one"
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "14268:14268"
      - "9411:9411"
      - "16686:16686"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
  iaassvc:
    build: ./service/cmd
    image: iaas:1.0.0
    ports:
      - "9191:9191"
